### ISSUE TITLE
Keeping in sync with BitBucket

### ISSUE THREAD

**Issue by sixtyfive** [fmalpartida/New-LiquidCrystal#1]
Hi! Thanks again, I just deleted my old fork and made a new one from this repository here. About your question: I've never used BitBucket (or indeed, Mercurial) before, so I wouldn't know. A bit of searching brought up [this piece](https://aaronsaray.com/2016/sync-bitbucket-and-github) - is that helpful?

**Comment by fmalpartida** [comment]
Thanks for the info. I will take a look and see if I can get both repos to be in synch.

**Comment by fmalpartida** [comment]
This library is now maintained here. Bitbucket stopped support for mercurial repos and closed all mercurial projects.
