### ISSUE TITLE
4004 LCD on I2C IO expander

### ISSUE THREAD

**Issue by YvedD** [fmalpartida/New-LiquidCrystal#2]
Hi community,

i have this 3.3v (and a 5.0v) 4004 LCD from eastrising (buydisplay)
[https://www.buydisplay.com/default/3-3v-5v-40x4-lcd-module-display-white-on-black-hd44780-controller](url)
I found on their website these documents regarding this type of display's
[https://www.buydisplay.com/download/manual/ERM4004-1_Series_Datasheet.pdf](url)

previous i used 2004 LCD with the I2C backpacks, but now, for a new project, with a Wemos Lolin 32S (ESP32 devboard) i would like (need?) to connect by I2C to save most of the pins on the devboard.
I tried different things, but nothing used to work out for me...

Was anyone capable of achieving this up so far? I read on the BitBucket thread, that using 2 instances of the library's I2C solution could be a helpfull thing, but i did not manage to get it to work
second question is : i have multiple I2C backpacks in the shelf, could one use 2 backpack on two different I2C adresses, for this type of display, it would mean more soldering or PCB prototyping, but if it would help that would be a minor problem... only problem is that i do not know where to start with all of this...

Any help to set me in the correct direction would be awesome!

Thanks in Advance,
yves

**Comment by fmalpartida** [comment]
In general, if you are using 2 different LCDs connected to a I2C LCD expansion board, you would use 2 LCD instances.
